name: naruto

services:
  mysql:
    image: mysql:8.0.45
    container_name: naruto-mysql

    networks:
      - naruto

    environment:
      MYSQL_DATABASE: naruto
      MYSQL_ROOT_PASSWORD: root

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 3s
      retries: 10
      interval: 5s

    volumes:
      - db_data:/var/lib/mysql
      - ./naruto-init.sql:/docker-entrypoint-initdb.d/setup.sql
  java:
    build: .

    networks:
      - naruto

    ports:
      - 8081:8080

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/naruto?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
    name: naruto-db-data

networks:
  naruto:
    name: naruto
